Repository aryan-harsh/DS-Algo-Codes, pull requests merged in 2020-10, with the labels that each got.

#18 Added codes for bucketing, partitions etc
  InterviewBit/Array/Find Permutation.cpp
  InterviewBit/Array/First Missing Integer.cpp
  InterviewBit/Array/Leaders in an Array.cpp
  InterviewBit/Array/Noble Integer.cpp
  InterviewBit/Array/Wave Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 Adding two numbers represented by link list.
  Add_two_numbers_represented_as_linklist.cpp
  Dynamic Programming/0-1_knapsack.cpp
  Dynamic Programming/LCS
  Dynamic Programming/Longest_common_subsequence.cpp
  Dynamic Programming/Longest_increasing_subsequence.cpp
  Dynamic Programming/Subset_sum_problem.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, help wanted

#19 Added codes for binary search
  InterviewBit/Binary Search/Implement Power Function.cpp
  InterviewBit/Binary Search/Median of Array.cpp
  InterviewBit/Binary Search/Rotated Sorted Array Search.cpp
  InterviewBit/Binary Search/Simple Queries.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Added two pointer problems
  InterviewBit/Two Pointers/3 Sum Zero.cpp
  InterviewBit/Two Pointers/3 Sum.cpp
  InterviewBit/Two Pointers/Array 3 Pointers.cpp
  InterviewBit/Two Pointers/Container With Most Water.cpp
  InterviewBit/Two Pointers/Counting Triangles.cpp
  InterviewBit/Two Pointers/Diffk.cpp
  InterviewBit/Two Pointers/Intersection Of Sorted Arrays.cpp
  InterviewBit/Two Pointers/Max Continuous Series of 1s.cpp
  InterviewBit/Two Pointers/Merge Two Sorted Lists II.cpp
  InterviewBit/Two Pointers/Remove Duplicates from Sorted Array II.cpp
  InterviewBit/Two Pointers/Remove Duplicates from Sorted Array.cpp
  InterviewBit/Two Pointers/Remove Element from Array.cpp
  InterviewBit/Two Pointers/Sort by Color.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 Updated Readme
  InterviewBit/Binary Search/Matrix Search.cpp
  InterviewBit/Binary Search/Square Root of Integer.cpp
  InterviewBit/Strings/Count and Say.cpp
  InterviewBit/Strings/Longest Common Prefix.cpp
  InterviewBit/Strings/Palindrome String.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added GFG Must Do Coding Questions
  GeeksForGeeks - Must Do Coding Questions/Array/Count the triplets.cpp
  GeeksForGeeks - Must Do Coding Questions/Array/Subarray Sum.cpp
Labels: hacktoberfest-accepted
